/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export function asyncAdd(num1: number, num2: number): Promise<number>
export class Mmap {
  path: string
  maxSize: number
  constructor(path: string, maxSize: number)
  write(data: string): void
  read(): void
}
export class GpioControl {
  constructor()
  info(): void
  setMode(): void
  setVal(): void
}
