/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class GpioControl {
  constructor(base: number, offset: number)
  setVal(offset: number, val: number): void
  getVal(offset: number): number
}
